# Generated by Django 4.0.1 on 2022-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_pokemon', models.ImageField(upload_to='fotos/%d%m%Y')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('numero_pokedex', models.CharField(max_length=100)),
                ('habilidade1', models.CharField(max_length=100)),
                ('habilidade2', models.CharField(blank=True, max_length=100, null=True)),
                ('altura', models.FloatField()),
                ('status_hp', models.CharField(max_length=100)),
                ('status_ataque', models.CharField(max_length=100)),
                ('status_defesa', models.CharField(max_length=100)),
                ('status_ataque_especial', models.CharField(max_length=100)),
                ('status_defesa_especial', models.CharField(max_length=100)),
                ('status_velocidade', models.CharField(max_length=100)),
                ('tipo1', models.CharField(max_length=100)),
                ('tipo2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
